# Generated by Django 5.2.6 on 2025-10-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='lien_exercice',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='lien_video',
        ),
        migrations.AddField(
            model_name='cours',
            name='contenu',
            field=models.TextField(blank=True, help_text='Contenu détaillé du cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LienCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type_lien', models.CharField(choices=[('video', 'Vidéo'), ('exercice', 'Exercice'), ('document', 'Document'), ('ressource', 'Ressource externe'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='cours.cours')),
            ],
            options={
                'verbose_name': 'Lien',
                'verbose_name_plural': 'Liens',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
